# See https://developer.github.com/v3/repos/#edit for all available settings.
repository:
  name: org-settings
  description: Organisational Settings
  homepage: https://vikash-kothary.github.io/org-settings
  topics: probot-app, github-app
  private: false
  has_issues: true
  has_wiki: true
  has_downloads: true
  default_branch: develop
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false

# Labels: define labels for Issues and Pull Requests
#labels:
#  - name: bug
#    color: CC0000
#  - name: feature
#    color: 336699
#  - name: first-timers-only
#    # include the old name to rename and existing label
#    oldname: Help Wanted


# Milestones: define milestones for Issues and Pull Requests
#milestones:
#  - title: milestone-title
#    description: milestone-description
#    # The state of the milestone. Either `open` or `closed`
#    state: open

# Collaborators: give specific users access to this repository.
collaborators:
  # * `pull` - can pull, but not push to or administer this repository.
  # * `push` - can pull and push, but not administer this repository.
  # * `admin` - can pull, push and administer this repository.
  - username: vikashkothary
    permission: admin

  - username: vikashkotharywork
    permission: admin

# NOTE: The APIs needed for teams are not supported yet by GitHub Apps
# https://developer.github.com/v3/apps/available-endpoints/
#teams:
#  - name: core
#    permission: admin
#  - name: docs
#    permission: push

# https://developer.github.com/v3/repos/branches/#update-branch-protection
branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        # Specify which users and teams can dismiss pull request reviews. Pass an empty dismissal_restrictions object to disable. User and team dismissal_restrictions are only available for organization-owned repositories. Omit this parameter for personal repositories.
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        # Required. The list of status checks to require in order to merge into this branch
        contexts: []
      # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
      enforce_admins: true
      # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
      restrictions:
        users: []
        teams: []

  - name: develop
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
      restrictions:
        users: []
        teams: []